---
title: "Lab 03"
author: "Yuhong Hu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(leaflet)
library(lubridate)
```

## Step1. Read in the data
First download and then read in with data.table:fread()
```{r}
if(!file.exists('met_all.gz')){
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", timeout = 60)
}

met <- data.table::fread("met_all.gz")
```

## Step2. Check the dimensions, headers, footers. 
2377343 rows and 30 columns.
```{r}
dim (met)
head(met)
tail(met)

```

## Step3. Take a look at the variables.
```{r}
str(met)
```

## Step4. Take a closer look at the key variables.
```{r}
table(met$year)
table(met$day)
table(met$hour)
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)

met[met$elev==9999.0] <- NA
summary(met$elev)

met <- met[temp>-40]
met2 <- met[order(temp)]
head(met2)
```
## Step5.Check the data against an external data source.
```{r}
met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)
```

## Step6. Calculate summary statistics
```{r}
elev <- met[elev==max(elev)]
summary(elev)

cor(elev$temp, elev$wind.sp, use="complete")

cor(elev$temp, elev$hour, use="complete")

cor(elev$wind.sp, elev$day, use="complete")

cor(elev$wind.sp, elev$hour, use="complete")

cor(elev$temp, elev$day, use="complete")


```

## Step7. Exploratory graphs
```{r}
hist(met$elev, breaks=100)

hist(met$temp)

hist(met$wind.sp)

leaflet(elev) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)


elev$date <- with(elev, ymd_h(paste(year, month, day, hour, sep= ' ')))
summary(elev$date)

elev <- elev[order(date)]
head(elev)

plot(elev$date, elev$temp, type='l')

plot(elev$date, elev$wind.sp, type='l')
```

